### PR TITLE
Fix NPE due to invalid back reference names

### PR DESCRIPTION
**Pull request by markusheiden**

### CODE REVIEW

**Comment by arey** [comment]
Do you need a maven release for this fix?

**Comment by markusheiden** [comment]
Currently not, because there is still a problem in a special edge case I need to fix first.

**Comment by markusheiden** [comment]
@arey I changed my mind: Please create a release. The "edge case" was a problem not related to this lib.

**Comment by arey** [comment]
Version 5.2.3 has been released.

**Pull request merged**
